language: node_js
sudo: false
node_js:
- 'node'
install:
- npm install
- gulp init
script:
- gulp build # this should be gulp test eventually
after_success:
- gulp dist
- ./deploy.sh
env:
  global:
    GH_REPO: YoloDev/aurelia-pagination.git
    secure: SuuSoDjy0OKI3XQoSCInuXSrh0L7fiGr3yS9Hl8LH1PEVmhzBMH++BZjT32780RfGagQ0GZjGInL6o39kKa3NPWnEJMA6/sADGX/WP/bykBh4hiRC0oI+jOL4v3mj+rSlrnvZY0th0ebGcJpHv52aLiWplvPn8DNL3kOW82uyKelU9hvsy/3qOc4aLu9IYF1gweAJHmZXhz3uaOlpB0LhA6zXZtJgd3muGwz3nnNjg3rMUKMEff/vFWag4NrvJtOMFAgs0GZ4Rb5MtaiN69rDrCL7nRhUjpmaJB0vChEwMEa5PqHVINwggpNxHXrC6ZSLvQEV0kg3ogS+x3G31SqdZ8UVCfQkq/5qWaO7EjCm/MzzGACBM+pjq3B257WPCCc50sUAXAWgiqPKBb104p9VdjrGRl8cA/DaU3lsmEM56mQVI1RMWqj6cjqP7cgRo+nZ0JHxKNXj09fhGNMlvOzW6gCIXZEajXO3IG17SPW3SWf74HGP5icH1jwF8Okf67uEvE8FuW9nx7EfLCR8IrIHw7pkZ81nrbGUm3QSj6KpYgldYLXLUX3ya904d/nzC3DXgIJGf2XvxBAqY1eBI+cEHpJm87eLk/+OnHjjDBVU2YHYFtB7u/KcCVdMluemeah+AMN0HmrsLduUOMMkhbN1OTS3qQzr+aG5faHbaBwx9s=
