language: node_js
sudo: false
node_js:
- 'node'
before_install:
- npm install -g jspm
- jspm config registries.github.remote https://github.jspm.io -y
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN -y
- jspm config registries.github.maxRepoSize 0 -y
- jspm config registries.github.handler jspm-github -y
install:
- npm install
- gulp init
script:
- gulp build # this should be gulp test eventually
after_success:
- gulp dist
- "./deploy.sh"