language: node_js
sudo: false
node_js:
- 'node'
before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN -y
install:
- npm install
- gulp init
script:
- gulp build # this should be gulp test eventually
after_success:
- gulp dist
- "./deploy.sh"